# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-framework-apollo-contentful

frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs18.x
  environment:
    CONTENTFUL_SPACE_ID: ${env:CONTENTFUL_SPACE_ID}
    CONTENTFUL_DELIVERY_API_TOKEN: ${env:CONTENTFUL_DELIVERY_API_TOKEN}

# The `functions` block defines what code to deploy
functions:
  graphql:
    handler: src/handlers/graphql.server
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
    environment:
      SLS_STAGE: ${sls:stage}
  healthcheck:
    handler: src/handlers/healthcheck.handler
    events:
      - http:
          path: healthcheck
          method: get
  moviesByGenre:
    handler: src/handlers/moviesByGenre.handler
    events:
      - http:
          path: genre/movies
          method: get
          cors: true
  genreById:
    handler: src/handlers/genreById.handler
    events:
      - http:
          path: movies/genre/{id}
          method: get
          cors: true
